Update issue templates
Magisk-Modules-Alt-Repo/submission pull request #203
Opened 2023-11-19 12:41 UTC by DerGoogler

Using new GitHub Issue forms. 

(@Atrate)

2023-11-19 15:13 UTC, Atrate commented
Could you enable issues in your repo so I can test them out?

2023-11-21 15:42 UTC, DerGoogler commented
@Atrate,

I have enabled issues, you can try it now. 

> Sorry for the late reply

2023-11-21 18:55 UTC, Atrate requested changes

2023-11-21 18:55 UTC, Atrate commented on .github/ISSUE_TEMPLATE/module-submission.yml
> +      label: Link
`label: Link` -> `label: Module repository link`

2023-11-21 18:55 UTC, Atrate commented on .github/ISSUE_TEMPLATE/module-submission.yml
> +      label: Link
`label: Link` -> `label: Source code link (for compiled binaries/APKs)`

2023-11-21 18:55 UTC, Atrate commented on .github/ISSUE_TEMPLATE/module-submission.yml
> +      placeholder: None
`placeholder: None` -> `placeholder: https://www.github.com/username/repo`

2023-11-21 19:09 UTC, DerGoogler commented
@Atrate , fixed

2023-11-21 21:05 UTC, Atrate approved these changes

2023-11-21 21:05 UTC, merged

2023-11-21 21:08 UTC, Atrate commented
@DerGoogler Thanks!